name: CMake

on: 
  pull_request: 
    branches: 
      - master
    types: 
      - opened
      - synchronize
      - reopened
  push: 
    branches: 
      - CI

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: Testing
        submodules: recursive
    
    - name: Install dependencies
      run: sudo apt install -y cmake g++-mingw-w64-x86-64 make libgl1-mesa-dev libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Configure CMake
      shell: bash
      run: cmake -S ./ -B ./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      run: cmake --build ./build

    - uses: actions/upload-artifact@v3
      with:
        name: mdlshit_linux_x64
        path: build
  
#  build_mingw:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        ref: Testing
#        submodules: recursive
#      
#    - name: Install dependencies
#      run: sudo apt install -y cmake g++-mingw-w64-x86-64 make libgl1-mesa-dev libx11-dev libxext-dev libxrandr-dev
#
#    - name: Configure CMake
#      shell: bash
#      run: cmake -S ./ -B ./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE="$GITHUB_WORKSPACE/glew-cmake/mingw.cmake"
#
#    - name: Build
#      shell: bash
#      run: cmake --build ./build
#
#    - uses: actions/upload-artifact@v3
#      with:
#        name: mdlshit_windows_mingw_x64
#        path: build


  build_mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: Testing
        submodules: recursive
    
    - name: Configure CMake
      shell: bash
      run: cmake -S ./ -B ./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      run: cmake --build ./build

    - uses: actions/upload-artifact@v3
      with:
        name: mdlshit_osx_x64
        path: build

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: Testing
        submodules: recursive
    
    - name: Configure CMake
      shell: bash
      run: cmake -S ./ -B ./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      run: cmake --build ./build
    
    - uses: actions/upload-artifact@v3
      with:
        name: mdlshit_windows_x86
        path: build
